### ISSUE TITLE
[BUG] The Birthday command is not updating the user's birthday

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/BirthdayBot#1]
If a user has already logged their birthday once, they should be able to update it

**Comment by KRHero03** [comment]
Hello,

I may be wrong, but were you trying to "upsert" the birthday in the file src/commands/birthday.js Line 31?
If so, I feel you missed the upsert=true parameter along with new=true parameter.

I found that here: https://mongoosejs.com/docs/tutorials/findoneandupdate.html

Read the Upsert section.

Thanks.

**Comment by tomassirio** [comment]
I'll give it a read, thanks

**Comment by Tails128** [comment]
Could you assign it to me? I have fixed it while implementing the birthdays command

**Comment by Tails128** [comment]
@tomassirio fix submitted, please check it asap so I can pr the birthdays command

**Comment by tomassirio** [comment]
There you go

**Comment by Tails128** [comment]
thanks!
