### ISSUE TITLE
[Feature] Develop the birthdays command

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/BirthdayBot#2]
The birthdays command should return a message with all the birthdays of the server

**Comment by Tails128** [comment]
Mind if I take this issue?

**Comment by tomassirio** [comment]
Sure!

**Comment by Tails128** [comment]
Hey, it seems like if two users add their birthday via the `birthday` command only one is saved

**Comment by tomassirio** [comment]
Hmm, that seems like another bug on the birthday command. It should save a birthday for every member

**Comment by Tails128** [comment]
Could you open an issue and assign it to me? I am fixing it
(see answer in `[BUG] The Birthday command is not updating the user's birthday `, they are related.)

**Comment by tomassirio** [comment]
Sure. I'll need you to comment in the issue in order to assign it

**Comment by tomassirio** [comment]
My bad, there is already an issue [#1](https://github.com/tomassirio/BirthdayBot/issues/1l)
