### ISSUE TITLE
[Feature] Develop the nextBirthday command

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/BirthdayBot#3]
The nextBirthday command should return a message with the next member having their birthday

**Comment by ealvarez968** [comment]
Hello, this sounds interesting, How can I help ?

**Comment by tomassirio** [comment]
You could start by modifying the nextBirthday command. You should retrieve the next birthday and send it on a message on the channel were the bot was invoked. Join us in the [discord server ](https://discord.gg/wtrfB7)so we keep discussing this
