### ISSUE TITLE
[Feature] The bot should create a text channel to announce every birthday

### ISSUE THREAD

**Issue by tomassirio** [tomassirio/BirthdayBot#6]
There should be a new channel every time the bot is logged to a new server in which the birthday announcements will be placed

**Comment by b2pacific** [comment]
I would like to work on this issue.

**Comment by tomassirio** [comment]
Sure! I'll assign it to you

**Comment by tomassirio** [comment]
Hey @b2pacific I just pushed a change on the pull request you uploaded. There was a bug because you were asking for the "Wishes" channel. However, discord stores it's channels on lowercase. So I got infinite wishes channels hahaha
